Repository hylang/hy, pull requests merged in 2021-03, with the labels that each got.

#1985 Feature: Add callable for macro to core
  NEWS.rst
  docs/cheatsheet.json
  hy/core/macros.hy
  tests/native_tests/core.hy
Labels: feature

#1979 Implement Hy builtins as actual builtins
  NEWS.rst
  docs/api.rst
  docs/cheatsheet.json
  docs/language/interop.rst
  docs/whyhy.rst
  hy/__init__.py
  hy/cmdline.py
  hy/compiler.py
  hy/contrib/destructure.hy
  hy/contrib/hy_repr.hy
  hy/contrib/pprint.hy
  hy/contrib/walk.hy
  hy/core/__init__.py
  hy/core/bootstrap.hy
  hy/core/language.hy
  hy/core/macros.hy
  hy/core/shadow.hy
  hy/extra/reserved.hy
  hy/importer.py
  hy/lex/__init__.py
  hy/macros.py
  tests/compilers/test_ast.py
  tests/importer/test_importer.py
  tests/native_tests/comprehensions.hy
  tests/native_tests/contrib/destructure.hy
  tests/native_tests/contrib/hy_repr.hy
  tests/native_tests/contrib/slicing.hy
  tests/native_tests/contrib/test_pprint.hy
  tests/native_tests/core.hy
  tests/native_tests/extra/reserved.hy
  tests/native_tests/language.hy
  tests/native_tests/mangling.hy
  tests/native_tests/native_macros.hy
  tests/native_tests/operators.hy
  tests/native_tests/quote.hy
  tests/resources/bin/require_and_eval.hy
  tests/test_bin.py
Labels: backend

#2010 Fix: test eval can see locals
  tests/native_tests/language.hy
Labels: bug

#2009 Fix: Add test for empty decorator call
  tests/native_tests/tag_macros.hy
Labels: bug
